CREATE TABLE products(
CODE VARCHAR(200) NOT NULL,
NAME VARCHAR(200) NOT NULL,
DESCRIPTION TEXT,
price DECIMAL(15,2) NOT NULL DEFAULT 0,
stock INT NOT NULL DEFAULT 0,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(CODE)
);



